# Ethical Hacking 2026
project:
  type: book
  output-dir: docs

book:
  title: "Ethical Hacking 2026"
  author: "Diego Saavedra"
  site-url: "https://statick88.github.io/ethical-hacking-2026/"
  favicon: images/hacking.png
  downloads: [pdf, epub]
  sidebar:
    style: docked
    search: true
  page-footer:
    left: |
      Ethical Hacking 2026 por Diego Saavedra
    right: |
      [Acerca de](/about.qmd) | [Licencia](/license.qmd)
  chapters:
    - index.qmd
    - part: "Contenido"
      chapters:
        - contenido/unidad1.qmd
        - contenido/unidad2.qmd
        - contenido/unidad3.qmd
        - contenido/unidad4.qmd
        - contenido/unidad5.qmd
        - contenido/unidad6.qmd
        - contenido/unidad7.qmd
        - contenido/unidad8.qmd
    - part: "Laboratorios"
      chapters:
        - labs/lab-unidad1.md
        - labs/lab-unidad2.md
        - labs/lab-unidad3.md
        - labs/lab-unidad4.md
        - labs/lab-unidad5.md
        - labs/lab-unidad6.md
        - labs/lab-unidad7.md
        - labs/lab-unidad8.md
    - part: "Evaluación"
      chapters:
        - quizzes/unidad1.md
        - quizzes/unidad2.md
        - quizzes/unidad3.md
        - quizzes/unidad4.md
        - quizzes/unidad5.md
        - quizzes/unidad6.md
        - quizzes/unidad7.md
        - quizzes/unidad8.md
    - part: "Anexos"
      chapters:
        - anexos/anexo-bash-scripting.qmd
        - anexos/anexo-docker.qmd
        - anexos/anexo-maquinas-virtuales.qmd
    - part: "Información"
      chapters:
        - about.qmd
        - license.qmd

format:
  html:
    theme:
      - solar
      - custom.scss
    css:
      - css/styles.css
      - custom.css
  pdf:
    documentclass: scrbook
  epub:
    cover-image: images/hacking.png

execute:
  echo: false
